version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - "8000:8000"
    networks:
      - local-network
  
  stepsfunctions:
    image: amazon/aws-stepfunctions-local
    container_name: stepsfunctions
    ports:
      - "8083:8083"
    networks: 
      - local-network

networks:
  local-network:
    name: hosting-compare
    driver: bridge